// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://coacrjockjoubribhwgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvYWNyam9ja2pvdWJyaWJod2dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMDc0NDYsImV4cCI6MjA2OTg4MzQ0Nn0.GZma5sqHAL9Iu_laXHYY-HpXNOWCHaiX5k6aYQ9slTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});